In [11]:
from sklearn.utils import shuffle
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

Using TensorFlow backend.
/Users/okamurakento/miniconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/Users/okamurakento/miniconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/Users/okamurakento/miniconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [13]:
M = 2
K = 3
n = 100
N = n * K

In [14]:
X1 = np.random.randn(n, M) + np.array([0, 10])
X2 = np.random.randn(n, M) + np.array([5, 5])
X3 = np.random.randn(n, M) + np.array([10, 0])
Y1 = np.array([[1, 0, 0] for i in range(n)])
Y2 = np.array([[1, 0, 0] for i in range(n)])
Y3 = np.array([[1, 0, 0] for i in range(n)])

X = np.concatenate((X1, X2, X3), axis=0)
Y = np.concatenate((Y1, Y2, Y3), axis=0)

In [16]:
model = Sequential()
model.add(Dense(input_dim=M, units=K))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy', optimizer=SGD(lr=0.1))

In [17]:
minibatch_size = 50
model.fit(X, Y, epochs=20, batch_size=minibatch_size)

Epoch 1/20
300/300 [==============================] - 0s 322us/step - loss: 0.8085
Epoch 2/20
300/300 [==============================] - 0s 111us/step - loss: 0.0113
Epoch 3/20
300/300 [==============================] - 0s 61us/step - loss: 0.0070
Epoch 4/20
300/300 [==============================] - 0s 160us/step - loss: 0.0052
Epoch 5/20
300/300 [==============================] - 0s 163us/step - loss: 0.0042
Epoch 6/20
300/300 [==============================] - 0s 107us/step - loss: 0.0036
Epoch 7/20
300/300 [==============================] - 0s 95us/step - loss: 0.0031
Epoch 8/20
300/300 [==============================] - 0s 113us/step - loss: 0.0027
Epoch 9/20
300/300 [==============================] - 0s 86us/step - loss: 0.0025
Epoch 10/20
300/300 [==============================] - 0s 131us/step - loss: 0.0023
Epoch 11/20
300/300 [==============================] - 0s 133us/step - loss: 0.0021
Epoch 12/20
300/300 [==============================] - 0s 110us/step - loss: 0.0019
Epoc

In [18]:
X_, Y_ = shuffle(X, Y)
classes = model.predict_classes(X_[0:10], batch_size=minibatch_size)
prob = model.predict_proba(X_[0:10], batch_size=1)

In [19]:
print('classified:')
print(np.argmax(model.predict(X_[0:10]), axis=1) == classes)
print()
print('output probability:')
print(prob)

classified:
[ True  True  True  True  True  True  True  True  True  True]

output probability:
[[  9.99875546e-01   9.91023917e-05   2.54121605e-05]
 [  9.99564946e-01   2.18823843e-04   2.16260451e-04]
 [  9.99470532e-01   3.20920692e-04   2.08488767e-04]
 [  9.99843478e-01   8.18366898e-05   7.46658843e-05]
 [  9.99517679e-01   2.29585043e-04   2.52737053e-04]
 [  9.98751044e-01   9.60760110e-04   2.88156036e-04]
 [  9.99249279e-01   4.65931429e-04   2.84858921e-04]
 [  9.99345601e-01   3.05897993e-04   3.48487985e-04]
 [  9.99381065e-01   4.17607749e-04   2.01360192e-04]
 [  9.99837637e-01   1.10920650e-04   5.14009080e-05]]
